project:
  type: website
  output-dir: docs/
  pre-render: snakemake -c 1 prerender
  post-render: snakemake -c 1 postrender

execute:
  freeze: auto

website:
  title: "sovacool.dev"
  site-url: https://sovacool.dev
  repo-url: https://github.com/kelly-sovacool/kelly-sovacool.github.io
  favicon: images/favicon-32x32.png
  google-analytics: "G-4XQKSHWZY6"
  twitter-card:
    creator: "@kelly_sovacool"
  open-graph: true
  search:
    location: navbar
    type: textbox
  navbar:
    right:
      - text: "About"
        href: index.html
      - text: "CV"
        href: "cv/index.html"
      - text: "Posts"
        href: posts.html

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    embed-resources: true
