project:
  type: website
  output-dir: docs/

execute:
  freeze: auto

website:
  title: "sovacool.dev"
  favicon: images/favicon-32x32.png
  google-analytics: G-4XQKSHWZY6
  search:
    location: navbar
    type: textbox
  navbar:
    left:
      - icon: github
        href: https://github.com/kelly-sovacool
    right:
      - text: "About"
        href: index.html
      - text: "Posts"
        href: posts.html
      - text: "CV"
        href: /latex-cv/cv_KLS.pdf
      - text: "Publications"
        href: pubs.html
      - icon: fa fa-rss
        href: posts.xml 

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
