project:
  type: website
  output-dir: _site/
  pre-render: snakemake -c 1 prerender
  post-render: snakemake -c 1 postrender

execute:
  freeze: auto

website:
  title: "sovacool.dev"
  site-url: https://sovacool.dev
  repo-url: https://github.com/kelly-sovacool/kelly-sovacool.github.io
  repo-actions: [edit, issue]
  favicon: images/favicon-32x32.png
  google-analytics: "G-HKN2N6YZGT"
  open-graph: true
  search:
    location: navbar
    type: textbox
  navbar:
    right:
      - text: "About"
        href: index.html
      - text: "CV"
        href: "cv/index.html"
      - text: "Posts"
        href: posts.html
      - icon: rss
        href: index.xml

format:
  html:
    theme:
      light:
        - flatly
        - styles.scss
      dark:
        - darkly
        - styles.scss
    embed-resources: true
