name: website
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - aioeasywebdav=2.4.0
  - aiohttp=3.8.3
  - aiosignal=1.3.1
  - amply=0.1.5
  - anyio=3.6.2
  - appdirs=1.4.4
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.1.0
  - async-timeout=4.0.2
  - attmap=0.13.2
  - attrs=22.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bcrypt=3.2.2
  - beautifulsoup4=4.11.1
  - bibtexparser=1.4.0
  - bleach=5.0.1
  - boto3=1.26.15
  - botocore=1.29.15
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.9.24
  - cachetools=5.2.0
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - coin-or-cbc=2.10.8
  - coin-or-cgl=0.60.6
  - coin-or-clp=1.17.7
  - coin-or-osi=0.108.7
  - coin-or-utils=2.11.6
  - coincbc=2.10.8
  - colorama=0.4.6
  - commonmark=0.9.1
  - configargparse=1.5.3
  - connection_pool=0.0.3
  - cryptography=38.0.3
  - dataclasses=0.8
  - datrie=0.8.2
  - debugpy=1.6.3
  - decorator=5.1.1
  - defusedxml=0.7.1
  - docutils=0.19
  - dpath=2.0.6
  - dropbox=11.36.0
  - entrypoints=0.4
  - exceptiongroup=1.0.4
  - executing=1.2.0
  - filechunkio=1.8
  - filelock=3.8.0
  - flit-core=3.8.0
  - frozenlist=1.3.3
  - ftputil=5.0.4
  - future=0.18.2
  - gettext=0.21.1
  - gitdb=4.0.9
  - gitpython=3.1.29
  - glib=2.74.1
  - glib-tools=2.74.1
  - google-api-core=2.10.2
  - google-api-python-client=2.66.0
  - google-auth=2.14.1
  - google-auth-httplib2=0.1.0
  - google-cloud-core=2.3.2
  - google-cloud-storage=2.6.0
  - google-crc32c=1.1.2
  - google-resumable-media=2.4.0
  - grpcio=1.49.1
  - gst-plugins-base=1.21.1
  - gstreamer=1.21.1
  - httplib2=0.21.0
  - icu=70.1
  - idna=3.4
  - importlib-metadata=5.0.0
  - importlib_resources=5.10.0
  - iniconfig=1.1.1
  - ipykernel=6.17.1
  - ipython=8.6.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.2
  - jedi=0.18.1
  - jinja2=3.1.2
  - jmespath=1.0.1
  - jpeg=9e
  - jsonschema=4.17.0
  - jupyter=1.0.0
  - jupyter_client=7.4.6
  - jupyter_console=6.4.4
  - jupyter_core=5.0.0
  - jupyter_server=1.23.2
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=3.0.3
  - krb5=1.19.3
  - libabseil=20220623.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=15.0.4
  - libclang13=15.0.4
  - libcrc32c=1.1.2
  - libcxx=14.0.6
  - libedit=3.1.20191231
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.74.1
  - libgrpc=1.49.1
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.4
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.38
  - libpq=14.5
  - libprotobuf=3.21.9
  - libsodium=1.0.18
  - libsqlite=3.39.4
  - libvorbis=1.3.7
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=15.0.5
  - logmuse=0.2.6
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - multidict=6.0.2
  - mysql-common=8.0.31
  - mysql-libs=8.0.31
  - nbclassic=0.4.8
  - nbclient=0.7.0
  - nbconvert=7.2.5
  - nbconvert-core=7.2.5
  - nbconvert-pandoc=7.2.5
  - nbformat=5.7.0
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - nspr=4.32
  - nss=3.78
  - numpy=1.23.5
  - oauth2client=4.1.3
  - openssl=1.1.1s
  - packaging=21.3
  - pandas=1.5.2
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - paramiko=2.12.0
  - parso=0.8.3
  - pcre2=10.40
  - peppy=0.35.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.3.1
  - pkgutil-resolve-name=1.3.10
  - plac=1.3.5
  - platformdirs=2.5.2
  - pluggy=1.0.0
  - ply=3.11
  - prettytable=3.4.1
  - prometheus_client=0.15.0
  - prompt-toolkit=3.0.32
  - prompt_toolkit=3.0.32
  - protobuf=4.21.9
  - psutil=5.9.4
  - ptyprocess=0.7.0
  - pulp=2.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pygments=2.13.0
  - pynacl=1.5.0
  - pyopenssl=22.1.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.19.2
  - pysftp=0.2.9
  - pysocks=1.7.1
  - pytest=7.2.0
  - python=3.11.0
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-irodsclient=1.1.5
  - python_abi=3.11
  - pytz=2022.6
  - pyu2f=0.1.5
  - pyyaml=6.0
  - pyzmq=24.0.1
  - qt-main=5.15.6
  - qtconsole=5.4.0
  - qtconsole-base=5.4.0
  - qtpy=2.3.0
  - re2=2022.06.01
  - readline=8.1.2
  - requests=2.28.1
  - reretry=0.11.1
  - rich=12.6.0
  - rsa=4.9
  - s3transfer=0.6.0
  - send2trash=1.8.0
  - setuptools=65.5.1
  - setuptools-scm=7.0.5
  - sip=6.7.4
  - six=1.16.0
  - slacker=0.14.0
  - smart_open=6.2.0
  - smmap=3.0.5
  - snakemake=7.18.2
  - snakemake-minimal=7.18.2
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - sqlite=3.39.4
  - stack_data=0.6.1
  - stone=3.3.1
  - stopit=1.1.2
  - tabulate=0.9.0
  - terminado=0.17.0
  - throttler=1.2.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toposort=1.7
  - tornado=6.2
  - traitlets=5.5.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022f
  - ubiquerg=0.6.2
  - uritemplate=4.1.1
  - urllib3=1.26.11
  - veracitools=0.1.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.4.2
  - wheel=0.38.4
  - widgetsnbextension=4.0.3
  - wrapt=1.14.1
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.8.1
  - yte=1.5.1
  - zeromq=4.3.4
  - zipp=3.10.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - googleapis-common-protos==1.57.0
