name: website
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - jupyter=1
  - nbconvert=7
  - numpy=1
  - pandas=1
  - pandoc=3
  - pip
  - pytest=7
  - python=3.11
  - pyyaml=6
  - quarto=1.5
  - r-base=4
  - snakemake=7
  - snakemake-minimal=7
