[workspace]
authors = ["Kelly Sovacool <kelly@sovacool.dev>"]
channels = ["conda-forge", "bioconda"]
name = "sovacool.dev"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
bibtexparser = ">=1.4.1,<2"
jupyter = ">=1.1.1,<2"
nbconvert = ">=7.17.1,<8"
numpy = ">=2.5.3,<3"
pandas = ">=2.3.3,<3"
pip = ">=26.2.1,<27"
pytest = ">=9.1.1,<10"
python = "3.*"
pyyaml = ">=6.0.3,<7"
quarto = ">=1.9.38,<2"
r-base = "4.*"
r-here = ">=1.0.2,<2"
r-rmarkdown = ">=2.32,<3"
r-tidyverse = ">=2.0.0,<3"
snakemake = "7.*"
snakemake-minimal = "7.*"
