---
title: "Publications"
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    self_contained: true
---
<style>
d-article a {
  border-bottom: none;
  text-decoration: none;
  color: #2f65a7;
} /* remove hyperlink underlines until hover */
d-article a:hover { border-bottom:1px dotted; }
</style>

<!-- for dimensions badges -->
<script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<!-- for altmetrics badges -->
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script> 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE
                      )
```


<!--
[Google Scholar profile](https://scholar.google.com/citations?user=TlglgLgAAAAJ)-->

**\*** Indicates co-first author. Last updated: `r Sys.Date()`


```{r deps}
library(reticulate)
use_python('~/miniconda3/bin/python')
```

```{bash download_bib, results = FALSE}
wget https://raw.githubusercontent.com/kelly-sovacool/latex-cv/master/cv_KLS.bib -O cv_KLS.bib
```

```{python import_pubs}
from publications import *
entries = parse_entries()
```

<table style="width:100%">
  <tr>
    <th> </th>
    <th> </th>
    <th> </th>
    <th> </th>
  </tr>
```{python pubtable, results = 'asis'}
idx = len(entries)
for entry in entries:
    print("<tr>\n",
          f'<td  style="vertical-align:top">{idx}.',
          f'<td>{entry.bib}',
          f'<td>{entry.github_badge()}',
          f'<td>{entry.altmetric()}',
          f'<td>{entry.dimensions_badge()}',
          sep = "</td>\n",
          end = "</tr>\n")
    idx -= 1

```
</table>
