---
title: "Name change"
description: "⚭"
date: 2024-12-16
---

2024 was the best year of my life so far: I got married! 🎉

With marriage comes the question: what will you do with your last name?
For a variety of reasons I'm taking the most complicated and inconvenient route possible:

- Legally, my surname is hyphenated: **Sovacool-Caruthers**
- For all things work, professional, and academic-related, I am using my original surname: **Sovacool**
- In social settings, I go by my spouse's surname: **Caruthers**

If you're checking out this website,
chances are you're in my professional network and you should carry on calling me Kelly Sovacool.
I want to maintain continuity in my [publication record](/pubs.qmd) and professional networks,
so I am going to be fastidious about using Sovacool for work & academic settings.

If you know me primarily from outside work, you can call me Kelly Caruthers and
refer to us both as The Caruthers. In social settings, I'm not too picky about it
and will probably just roll with whatever you call me.

Using three variations of my last name is sure to generate endless opportunities for confusion,
but I like the flexibility it affords. Will it be worth it? Dunno!
I can be stubbornly perseverant and optimistic through silly things like self-inflicted paper work.
