---
title: "Bioinformatics Resources"
description: |
  Resources for Bioinformatics Software Development & Data Analysis
date: 2019-05-15
output:
  distill::distill_article:
    self_contained: false
    toc: true
categories:
  - Bioinformatics
  - Software Development
  - Data Analysis
  - Reproducibility
  - Python
  - R
  - git
---

I found myself sending some of the same links over and over again to people who asked questions related to bioinformatics. So it was time to compile all the links in one convenient place!

All of the resources linked below are free unless otherwise noted. This isn't intended to be an exhaustive list of all the resources available, just some of the ones I have come across and have found useful.

*Last updated: 2019-09-23*

## Programming
- [Software Carpentry](https://software-carpentry.org/lessons/): Intro lessons on the Unix shell, git, R, & Python.
- [Langmead Lab teaching materials](http://www.langmead-lab.org/teaching-materials/): cover classic bioinformatics algorithms.
- [Advent of Code](https://adventofcode.com/): small programming puzzles.
- [Stepik Bioinformatics Contest](https://bioinf.me/en/contest).

### Shell
- [Introduction to the Unix Shell](http://swcarpentry.github.io/shell-novice/) - Software Carpentry
- [Extra Unix Shell Material](http://carpentries-incubator.github.io/shell-extras/) - Software Carpentry
- [Introduction to the Command Line for Genomics](https://datacarpentry.org/shell-genomics/) - Data Carpentry
- [Oh My ZSH!](https://ohmyz.sh/): framework for managing your zsh configuration. I switched from bash to zsh and haven't looked back! ([Why zsh is cooler than your shell](https://www.slideshare.net/jaguardesignstudio/why-zsh-is-cooler-than-your-shell-16194692))

### Git
- [Version Control with Git](http://swcarpentry.github.io/git-novice/) - Software Carpentry
- [git documentation](https://git-scm.com/doc)
- [Learn Git Branching](http://learngitbranching.js.org/?NODEMO): interactive git visualizer
- [How to Write a Git Commit Message](https://chris.beams.io/posts/git-commit/) - Chris Beams
- Link your university email to [GitHub](https://education.github.com/benefits) to get pro/education features.
    - All users (Pro or free) get free unlimited private repositories on GitHub.
- [GitKraken](https://www.gitkraken.com/invite/xin2e3HK) has a nice GUI for interacting with git, GitHub, GitLab, etc. (Note that this is a referral link to be entered to win a Nintendo Switch.)

### Python
- [Software Carpentry lesson](http://swcarpentry.github.io/python-novice-inflammation)
- [Project Rosalind](http://rosalind.info/problems/locations/): learn Python & practice solving bioinformatics problems.
- [GWC Code demos](https://github.com/GWC-DCMB/codeDemos): introductory Python demos - [Girls Who Code @ UM-DCMB](http://umich.edu/~girlswc/)
- [GWC Challenge Questions](https://github.com/GWC-DCMB/challengeQuestions): practice solving problems - [Girls Who Code @ UM-DCMB](http://umich.edu/~girlswc/)
- [Python For Everybody](https://www.coursera.org/specializations/python) course on Coursera (free for UMich students) - Charles Severance
- [Object-Oriented Programming (OOP) in Python](https://realpython.com/python3-object-oriented-programming/) tutorial - RealPython
- Books:
    - [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/) - Jake VanderPlas
    - [Automate the Boring Stuff with Python](https://automatetheboringstuff.com/) - Al Sweigart
    - [Think Python: How to Think Like a Computer Scientist](http://greenteapress.com/thinkpython/html/index.html) - Allen Downey
    - [Dive Into Python 3](https://www.cmi.ac.in/~madhavan/courses/prog2-2012/docs/diveintopython3/index.html) - Mark Pilgrim
    - [Object-Oriented Programming in Python](https://python-textbok.readthedocs.io) - University of Cape Town
- Videos:
    - [Office Hours for BIOINF 529: Bioinformatic Concepts & Algorithms](https://www.youtube.com/channel/UCewko4qgzTUZFmydW2shcEg) - [Marcus Sherman](https://www.betteridiot.tech/)
    - [Transforming Code into Beautiful, Idiomatic Python](https://pyvideo.org/pycon-us-2013/transforming-code-into-beautiful-idiomatic-pytho.html) - Raymond Hettinger
    - [Beyond PEP 8 -- Best practices for beautiful intelligible code](https://youtu.be/wf-BqAjZb8M) - Raymond Hettinger

### R
- [Software Carpentry lesson](http://swcarpentry.github.io/r-novice-gapminder)
- [RStudio's interactive tutorials](https://rstudio.cloud/learn/primers)
- [Cheatsheets by RStudio](https://www.rstudio.com/resources/cheatsheets/)
- [Riffomonas minimalR](http://www.riffomonas.org/minimalR/): Intro to R tutorial with applications in microbiology - Pat Schloss
- [What is the Tidyverse?](https://rviews.rstudio.com/2017/06/08/what-is-the-tidyverse/)
- [Getting started with the Tidyverse](http://www.storybench.org/getting-started-with-tidyverse-in-r/)
- Books:
    - [R for Data Science](https://r4ds.had.co.nz/) - Hadley Wickham
    - [Mastering Software Development in R](https://bookdown.org/rdpeng/RProgDA/) - Roger Peng, Sean Kross, & Brooke Anderson
    - [Advanced R](https://adv-r.hadley.nz/) - Hadley Wickham
    - [R Packages](http://r-pkgs.had.co.nz/) - Hadley Wickham
    - [What they forgot to teach you about R](https://whattheyforgot.org/) - Jenny Bryan & Jim Hester
    - [Happy Git and GitHub for the useR](https://happygitwithr.com/) - Jenny Bryan & Jim Hester
    - [Fundamentals of Data Visualization](https://serialmentor.com/dataviz/) - Claus O. Wilke
    - [An Introduction to Statistical Learning with Applications in R](http://faculty.marshall.usc.edu/gareth-james/ISL/index.html) - Gareth James, Daniela Witten, Trevor Hastie, & Robert Tibshirani

## Reproducibility
- [Riffomonas reproducible research tutorial](http://www.riffomonas.org/reproducible_research/) - Pat Schloss
- [Snakemake](https://snakemake.readthedocs.io/en/stable/): Python-based workflow management system.
- [conda](https://conda.io/en/latest/): package, dependency, & environment manager.
    - [cheatsheet](https://conda.io/projects/conda/en/latest/user-guide/cheatsheet.html)
    - [Tutorial: conda on the cluster](https://github.com/um-dang/conda_on_the_cluster) - Will Close
- [How to Name Files](https://speakerdeck.com/jennybc/how-to-name-files) - Jenny Bryan

### Project organization
- Noble WS. **A quick guide to organizing computational biology projects**. 2009. PLOS Comput Biol. doi: [10.1371/journal.pcbi.1000424](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1000424).
- [Scientific project template](https://github.com/SchlossLab/new_project).
- [cookiecutter](https://cookiecutter.readthedocs.io/en/latest/) project templating tool.
- [How to Name Files](https://speakerdeck.com/jennybc/how-to-name-files) - Jenny Bryan

### Literate programming

#### R Markdown
- [How I use R Markdown to document my bioinformatics analyses](https://rachaellappan.github.io/rmarkdown/) - Rachael Lappan
- [RMarkdown for writing reproducible scientific papers](https://libscie.github.io/rmarkdown-workshop/handout.html) - Mike Frank & Chris Hartgerink
- [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/) - Yihui Xie, J. J. Allaire, Garrett Grolemund
- [Communicating with R Markdown](https://ysc-rmarkdown.netlify.com/)

#### Jupyter
- [Jupyter Notebooks for Performing and Sharing Bioinformatics Analyses](https://github.com/ljdursi/glbio-jupyter-workshop) - Jonathan Dursi
- [JupyterLab Documentation](https://jupyterlab.readthedocs.io/en/stable/)
- [Google Colab](https://colab.research.google.com) - free Jupyter notebook environment in the cloud.
  - We use this for teaching Python for data science in our [Girls Who Code club](http://umich.edu/~girlswc/).

### Documentation
- Lee BD (2018) **Ten simple rules for documenting scientific software**. PLoS Comput Biol 14(12): e1006561. doi: [10.1371/journal.pcbi.1006561](https://doi.org/10.1371/journal.pcbi.1006561).
- [docopt](http://docopt.org/): easily create & parse command-line interfaces. Available for Python, R, C++, & more.
- [Sphinx](http://www.sphinx-doc.org/en/master/) for creating documentation.
- [Read the Docs](https://docs.readthedocs.io/en/stable/) for hosting documentation.
- [Writing R package documentation](https://support.rstudio.com/hc/en-us/articles/200532317-Writing-Package-Documentation).
- [pkgdown](https://pkgdown.r-lib.org/): build a website for your R package.

## Editors
- [Atom](https://atom.io/): text editor. Additional packages for atom:
    - [Autosave on change](https://atom.io/packages/autosave-onchange)
    - [Markdown Preview](https://atom.io/packages/markdown-preview-plus)
    - [Markdown TOC](https://atom.io/packages/markdown-toc)
    - [Language LaTeX](https://atom.io/packages/language-latex)
- [PyCharm](https://www.jetbrains.com/pycharm/): IDE for Python.
    - The community edition is free, or link your university email to get the pro version for free.
    - Supports Snakemake syntax highlighting & Jupyter notebooks.
- [RStudio](https://www.rstudio.com/): IDE for R.
- [Kite](https://kite.com/): AI autocomplete for Python. Works in Atom, PyCharm, Vim, & more.

## Misc.
- [csvkit](https://csvkit.readthedocs.io/en/1.0.3/index.html): command-line tool for working with and converting to CSV format from Excel, JSON, etc.
- [Hypothesis](https://hypothesis.readthedocs.io/en/latest/) Python testing module.
