name: quarto

on:
    workflow_dispatch:
    push:
      branches:
        - main

permissions:
  contents: write
  pages: write

jobs:
    build-deploy:
      runs-on: ubuntu-latest

      steps:
        - name: Check out repository
          uses: actions/checkout@v4

        - name: Set up Quarto
          uses: quarto-dev/quarto-actions/setup@v2
          with:
            version: 1.4.550

        - uses: mamba-org/setup-micromamba@v1
          with:
            environment-file: environment.yml
            cache-environment: true
            cache-downloads: true

        - name: Quarto render
          run: quarto render
          shell: micromamba-shell {0}

        - name: Publish to GitHub Pages (and render) 
          uses: quarto-dev/quarto-actions/publish@v2
          with:
            target: gh-pages
            render: false
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
